# Generated by Django 5.2.11 on 2026-02-06 04:20

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('jobs', '0002_initial'),
        ('social', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='socialpost',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='social_posts_created', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='socialpost',
            name='job',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='social_posts', to='jobs.job'),
        ),
        migrations.AlterUniqueTogether(
            name='socialaccount',
            unique_together={('agency', 'platform'), ('company', 'platform')},
        ),
        migrations.AddIndex(
            model_name='socialpost',
            index=models.Index(fields=['job', 'platform'], name='social_post_job_id_bd6514_idx'),
        ),
        migrations.AddIndex(
            model_name='socialpost',
            index=models.Index(fields=['status', 'scheduled_at'], name='social_post_status_3c3be3_idx'),
        ),
    ]
