# Generated by Django 5.2.11 on 2026-02-19 05:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('social', '0002_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SocialTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('provider', models.CharField(choices=[('facebook', 'Facebook'), ('instagram', 'Instagram'), ('linkedin', 'LinkedIn'), ('twitter', 'Twitter/X')], max_length=20, unique=True)),
                ('title_format', models.CharField(help_text='Template for post title. Use {job_title}, {company}, {location}, {salary} placeholders', max_length=500)),
                ('include_salary', models.BooleanField(default=True)),
                ('hashtags', models.JSONField(blank=True, default=list)),
                ('utm_source', models.CharField(default='social', max_length=100)),
                ('utm_medium', models.CharField(default='post', max_length=100)),
                ('utm_campaign', models.CharField(default='job_posting', max_length=100)),
            ],
            options={
                'db_table': 'social_templates',
                'ordering': ['provider'],
            },
        ),
        migrations.AlterField(
            model_name='socialaccount',
            name='platform',
            field=models.CharField(choices=[('linkedin', 'LinkedIn'), ('twitter', 'Twitter/X'), ('facebook', 'Facebook'), ('instagram', 'Instagram')], max_length=20),
        ),
        migrations.AlterField(
            model_name='socialpost',
            name='platform',
            field=models.CharField(choices=[('facebook', 'Facebook'), ('instagram', 'Instagram'), ('linkedin', 'LinkedIn'), ('twitter', 'Twitter/X')], max_length=20),
        ),
        migrations.AlterField(
            model_name='socialpost',
            name='status',
            field=models.CharField(choices=[('queued', 'Queued'), ('pending', 'Pending'), ('scheduled', 'Scheduled'), ('posted', 'Posted'), ('failed', 'Failed')], default='pending', max_length=20),
        ),
    ]
