# Generated by Django 5.2.11 on 2026-02-06 04:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='EmailLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('to_email', models.EmailField(max_length=254)),
                ('subject', models.CharField(max_length=255)),
                ('template', models.CharField(max_length=100)),
                ('context', models.JSONField(default=dict)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('sent', 'Sent'), ('failed', 'Failed'), ('bounced', 'Bounced')], default='pending', max_length=20)),
                ('sent_at', models.DateTimeField(blank=True, null=True)),
                ('error_message', models.TextField(blank=True)),
                ('provider_id', models.CharField(blank=True, max_length=100)),
            ],
            options={
                'db_table': 'email_logs',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('notification_type', models.CharField(choices=[('application_received', 'New Application Received'), ('application_status', 'Application Status Update'), ('job_alert', 'Job Alert'), ('message', 'New Message'), ('job_expired', 'Job Expired'), ('credits_low', 'Credits Running Low'), ('system', 'System Notification')], max_length=30)),
                ('title', models.CharField(max_length=255)),
                ('message', models.TextField()),
                ('data', models.JSONField(blank=True, default=dict)),
                ('link', models.CharField(blank=True, max_length=500)),
                ('is_read', models.BooleanField(default=False)),
                ('read_at', models.DateTimeField(blank=True, null=True)),
                ('email_sent', models.BooleanField(default=False)),
                ('email_sent_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'notifications',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='NotificationPreference',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email_application_received', models.BooleanField(default=True)),
                ('email_application_status', models.BooleanField(default=True)),
                ('email_job_alerts', models.BooleanField(default=True)),
                ('email_messages', models.BooleanField(default=True)),
                ('email_job_expired', models.BooleanField(default=True)),
                ('email_credits_low', models.BooleanField(default=True)),
                ('email_marketing', models.BooleanField(default=False)),
                ('push_enabled', models.BooleanField(default=True)),
            ],
            options={
                'db_table': 'notification_preferences',
            },
        ),
    ]
