# Generated by Django 5.2.11 on 2026-02-13 22:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0002_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmailProvider',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('provider_type', models.CharField(choices=[('resend', 'Resend'), ('sendgrid', 'SendGrid'), ('postmark', 'Postmark'), ('mailgun', 'Mailgun')], max_length=20, unique=True)),
                ('name', models.CharField(max_length=100)),
                ('logo', models.CharField(blank=True, max_length=255)),
                ('connected', models.BooleanField(default=False)),
                ('api_key', models.CharField(blank=True, max_length=255)),
                ('status', models.CharField(choices=[('active', 'Active'), ('disconnected', 'Disconnected'), ('error', 'Error')], default='disconnected', max_length=20)),
                ('last_sync', models.DateTimeField(blank=True, null=True)),
                ('spf', models.CharField(choices=[('verified', 'Verified'), ('warning', 'Warning'), ('missing', 'Missing')], default='missing', max_length=10)),
                ('dkim', models.CharField(choices=[('verified', 'Verified'), ('warning', 'Warning'), ('missing', 'Missing')], default='missing', max_length=10)),
                ('dmarc', models.CharField(choices=[('verified', 'Verified'), ('warning', 'Warning'), ('missing', 'Missing')], default='missing', max_length=10)),
                ('webhook_enabled', models.BooleanField(default=False)),
                ('rate_limit', models.CharField(default='100/min', max_length=50)),
                ('region', models.CharField(default='us-east-1', max_length=50)),
                ('sending_domain', models.CharField(blank=True, max_length=255)),
                ('is_active', models.BooleanField(default=False)),
            ],
            options={
                'db_table': 'email_providers',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='EmailSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('default_from_name', models.CharField(default='Orion', max_length=100)),
                ('default_from_email', models.EmailField(default='noreply@orion.jobs', max_length=254)),
                ('reply_to_address', models.EmailField(blank=True, max_length=254)),
                ('sending_domain', models.CharField(default='orion.jobs', max_length=255)),
                ('unsubscribe_text', models.TextField(default='Unsubscribe from these emails')),
                ('include_unsubscribe', models.BooleanField(default=True)),
                ('max_emails_per_second', models.PositiveIntegerField(default=10)),
                ('max_emails_per_minute', models.PositiveIntegerField(default=100)),
                ('max_retries', models.PositiveIntegerField(default=3)),
                ('initial_backoff', models.PositiveIntegerField(default=60)),
                ('backoff_multiplier', models.FloatField(default=2.0)),
                ('production_mode', models.BooleanField(default=False)),
                ('kill_switch_enabled', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name_plural': 'Email settings',
                'db_table': 'email_settings',
            },
        ),
        migrations.CreateModel(
            name='EmailTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=255)),
                ('slug', models.SlugField(max_length=255, unique=True)),
                ('type', models.CharField(choices=[('Transactional', 'Transactional'), ('Marketing', 'Marketing'), ('System', 'System')], max_length=20)),
                ('status', models.CharField(choices=[('Published', 'Published'), ('Draft', 'Draft')], default='Draft', max_length=20)),
                ('subject', models.CharField(max_length=255)),
                ('preheader', models.CharField(blank=True, max_length=255)),
                ('html', models.TextField()),
                ('variables', models.JSONField(blank=True, default=list)),
                ('used_by', models.PositiveIntegerField(default=0)),
            ],
            options={
                'db_table': 'email_templates',
                'ordering': ['-updated_at'],
                'indexes': [models.Index(fields=['slug'], name='email_templ_slug_06a2df_idx'), models.Index(fields=['status', 'type'], name='email_templ_status_0d8c62_idx')],
            },
        ),
        migrations.CreateModel(
            name='EmailTrigger',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=255)),
                ('category', models.CharField(choices=[('Authentication', 'Authentication'), ('Applications', 'Applications'), ('Jobs', 'Jobs'), ('Billing', 'Billing'), ('System', 'System')], max_length=50)),
                ('event_key', models.CharField(max_length=100, unique=True)),
                ('status', models.BooleanField(default=True)),
                ('audience', models.CharField(choices=[('Candidates', 'Candidates'), ('Employers', 'Employers'), ('Agencies', 'Agencies'), ('All Users', 'All Users')], max_length=50)),
                ('last_sent', models.DateTimeField(blank=True, null=True)),
                ('sends_7d', models.PositiveIntegerField(default=0)),
                ('errors_7d', models.PositiveIntegerField(default=0)),
                ('provider', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='triggers', to='notifications.emailprovider')),
                ('template', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='triggers', to='notifications.emailtemplate')),
            ],
            options={
                'db_table': 'email_triggers',
                'ordering': ['category', 'name'],
                'indexes': [models.Index(fields=['event_key'], name='email_trigg_event_k_14d8ae_idx'), models.Index(fields=['status', 'category'], name='email_trigg_status_fb5db2_idx')],
            },
        ),
    ]
