# Generated by Django 5.2.11 on 2026-02-19 05:11

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketing', '0001_initial'),
        ('notifications', '0003_emailprovider_emailsettings_emailtemplate_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='emaillog',
            name='campaign',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='email_logs', to='marketing.campaign'),
        ),
        migrations.AddField(
            model_name='emaillog',
            name='journey_step',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='email_logs', to='marketing.journeystep'),
        ),
        migrations.AddIndex(
            model_name='emaillog',
            index=models.Index(condition=models.Q(('campaign__isnull', False)), fields=['campaign'], name='idx_email_log_campaign'),
        ),
    ]
