# Generated by Django 5.2.11 on 2026-02-23 02:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0007_slackinstallation_client_creds'),
    ]

    operations = [
        migrations.AddField(
            model_name='notificationpreference',
            name='email_billing',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='notificationpreference',
            name='email_job_status',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='notificationpreference',
            name='email_weekly_digest',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='notification',
            name='notification_type',
            field=models.CharField(choices=[('application_received', 'New Application Received'), ('application_status', 'Application Status Update'), ('job_alert', 'Job Alert'), ('job_pending_review', 'Job Pending Review'), ('job_approved', 'Job Approved'), ('job_rejected', 'Job Rejected'), ('message', 'New Message'), ('job_expired', 'Job Expired'), ('credits_low', 'Credits Running Low'), ('system', 'System Notification')], max_length=30),
        ),
    ]
