# Generated by Django 5.2.11 on 2026-02-25 04:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0008_add_job_status_billing_digest_fields'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='notification_type',
            field=models.CharField(choices=[('application_received', 'New Application Received'), ('application_status', 'Application Status Update'), ('job_alert', 'Job Alert'), ('job_pending_review', 'Job Pending Review'), ('job_approved', 'Job Approved'), ('job_rejected', 'Job Rejected'), ('message', 'New Message'), ('job_expired', 'Job Expired'), ('credits_low', 'Credits Running Low'), ('system', 'System Notification'), ('payment_success', 'Payment Successful'), ('payment_failed', 'Payment Failed'), ('payment_action_required', 'Payment Action Required'), ('subscription_past_due', 'Subscription Past Due')], max_length=40),
        ),
    ]
