# Generated by Django 5.2.11 on 2026-02-25 16:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0009_alter_notification_notification_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='emailsettings',
            name='webhook_secret',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='emailsettings',
            name='webhook_url',
            field=models.URLField(blank=True, default=''),
        ),
    ]
