# Generated by Django 5.2.11 on 2026-02-26 01:56

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0011_refactor_email_providers'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='EmailTemplateVersion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('version', models.PositiveIntegerField()),
                ('html', models.TextField()),
                ('subject', models.CharField(max_length=255)),
                ('preheader', models.CharField(blank=True, max_length=255)),
            ],
            options={
                'db_table': 'email_template_versions',
                'ordering': ['-version'],
            },
        ),
        migrations.RemoveIndex(
            model_name='emailtemplate',
            name='email_templ_status_0d8c62_idx',
        ),
        migrations.AddField(
            model_name='emailtemplate',
            name='subcategory',
            field=models.CharField(blank=True, choices=[('Authentication', 'Authentication'), ('Jobs', 'Jobs'), ('Applications', 'Applications'), ('Billing', 'Billing'), ('Alerts', 'Alerts'), ('Campaign', 'Campaign'), ('Promotional', 'Promotional'), ('Newsletter', 'Newsletter'), ('Coupon', 'Coupon'), ('Announcement', 'Announcement'), ('Default', 'Default'), ('Internal', 'Internal')], max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='emailtemplate',
            name='version',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='emailtemplate',
            name='status',
            field=models.CharField(choices=[('Published', 'Published'), ('Draft', 'Draft'), ('Archived', 'Archived')], default='Draft', max_length=20),
        ),
        migrations.AddIndex(
            model_name='emailtemplate',
            index=models.Index(fields=['status', 'type', 'subcategory'], name='email_templ_status_df1110_idx'),
        ),
        migrations.AddField(
            model_name='emailtemplateversion',
            name='saved_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='emailtemplateversion',
            name='template',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='versions', to='notifications.emailtemplate'),
        ),
        migrations.AlterUniqueTogether(
            name='emailtemplateversion',
            unique_together={('template', 'version')},
        ),
    ]
