# Generated by Django 5.2.11 on 2026-02-26 02:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0012_emailtemplateversion_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='emailsettings',
            name='dismissed_suggestions',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
