# Generated by Django 5.2.11 on 2026-02-26 02:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0013_emailsettings_dismissed_suggestions'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emailtrigger',
            name='audience',
            field=models.CharField(choices=[('Admin', 'Admin'), ('Agency', 'Agency'), ('Company', 'Company'), ('Candidate', 'Candidate'), ('All Users', 'All Users')], max_length=50),
        ),
        migrations.AlterField(
            model_name='emailtrigger',
            name='category',
            field=models.CharField(choices=[('Onboarding', 'Onboarding'), ('Activation', 'Activation'), ('Jobs', 'Jobs'), ('Billing', 'Billing'), ('Trust & Safety', 'Trust & Safety'), ('Support', 'Support'), ('Notifications', 'Notifications'), ('Marketing', 'Marketing'), ('System', 'System')], max_length=50),
        ),
    ]
