# Generated by Django 5.2.11 on 2026-02-27 05:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_alter_user_entity_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='entity_id',
            field=models.CharField(blank=True, db_index=True, editable=False, help_text='Unique 8-character alphanumeric identifier (generated on save)', max_length=10, unique=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='mfa_secret',
            field=models.TextField(blank=True, default=''),
        ),
    ]
