export const INDUSTRIES: { value: string; label: string }[] = [
  { value: "Aerospace & Defense", label: "Aerospace & Defense" },
  { value: "Agriculture", label: "Agriculture" },
  { value: "Arts & Design", label: "Arts & Design" },
  { value: "Automotive", label: "Automotive" },
  { value: "Biotechnology", label: "Biotechnology" },
  { value: "Construction", label: "Construction" },
  { value: "Consulting", label: "Consulting" },
  { value: "Consumer Goods", label: "Consumer Goods" },
  { value: "E-commerce", label: "E-commerce" },
  { value: "Education", label: "Education" },
  { value: "Energy & Utilities", label: "Energy & Utilities" },
  { value: "Environmental Services", label: "Environmental Services" },
  { value: "Fashion & Apparel", label: "Fashion & Apparel" },
  { value: "Finance & Banking", label: "Finance & Banking" },
  { value: "Food & Beverage", label: "Food & Beverage" },
  { value: "Government", label: "Government" },
  { value: "Healthcare", label: "Healthcare" },
  { value: "Hospitality & Tourism", label: "Hospitality & Tourism" },
  { value: "Human Resources", label: "Human Resources" },
  { value: "Information Services", label: "Information Services" },
  { value: "Insurance", label: "Insurance" },
  { value: "Legal Services", label: "Legal Services" },
  { value: "Logistics & Supply Chain", label: "Logistics & Supply Chain" },
  { value: "Manufacturing", label: "Manufacturing" },
  { value: "Marketing & Advertising", label: "Marketing & Advertising" },
  { value: "Media & Entertainment", label: "Media & Entertainment" },
  { value: "Mining & Metals", label: "Mining & Metals" },
  { value: "Nonprofit", label: "Nonprofit" },
  { value: "Pharmaceuticals", label: "Pharmaceuticals" },
  { value: "Professional Services", label: "Professional Services" },
  { value: "Real Estate", label: "Real Estate" },
  { value: "Retail", label: "Retail" },
  { value: "Sales", label: "Sales" },
  { value: "Security & Investigations", label: "Security & Investigations" },
  { value: "Sports & Recreation", label: "Sports & Recreation" },
  { value: "Staffing & Recruiting", label: "Staffing & Recruiting" },
  { value: "Technology", label: "Technology" },
  { value: "Telecommunications", label: "Telecommunications" },
  { value: "Transportation & Logistics", label: "Transportation & Logistics" },
  { value: "Venture Capital & Private Equity", label: "Venture Capital & Private Equity" },
  { value: "Other", label: "Other" },
]

export const INDUSTRY_LABELS = INDUSTRIES.map((i) => i.label)
