# Generated by Django 5.2.11

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('jobs', '0001_initial'),
        ('companies', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AIProviderConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(help_text='Display name for this configuration (e.g. "Groq - Llama 3.1 8B")', max_length=100)),
                ('provider', models.CharField(choices=[('anthropic', 'Anthropic (Claude)'), ('openai', 'OpenAI (GPT)'), ('openrouter', 'OpenRouter'), ('gemini', 'Google Gemini'), ('mistral', 'Mistral AI'), ('deepseek', 'DeepSeek'), ('groq', 'Groq'), ('xai', 'xAI (Grok)'), ('together', 'Together AI')], max_length=30)),
                ('base_url', models.URLField(blank=True, help_text='Custom API base URL for OpenAI-compatible providers')),
                ('api_key', models.TextField(help_text='Encrypted API key for the provider')),
                ('model', models.CharField(help_text='Model identifier (e.g. claude-sonnet-4-20250514, gpt-4o)', max_length=100)),
                ('is_active', models.BooleanField(default=False, help_text='Only one config can be active at a time')),
                ('max_requests_per_minute', models.PositiveIntegerField(default=30)),
                ('max_requests_per_day', models.PositiveIntegerField(default=5000)),
                ('cost_per_1k_input_tokens', models.DecimalField(decimal_places=5, default=0, help_text='Cost per 1000 input tokens in USD', max_digits=8)),
                ('cost_per_1k_output_tokens', models.DecimalField(decimal_places=5, default=0, help_text='Cost per 1000 output tokens in USD', max_digits=8)),
                ('seo_generation_enabled', models.BooleanField(default=True)),
                ('social_generation_enabled', models.BooleanField(default=True)),
                ('auto_generate_on_publish', models.BooleanField(default=False, help_text='Auto-generate SEO meta + social posts when a job is published')),
            ],
            options={
                'verbose_name': 'AI Provider Config',
                'verbose_name_plural': 'AI Provider Configs',
                'db_table': 'ai_provider_configs',
            },
        ),
        migrations.CreateModel(
            name='AIUsageLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('feature', models.CharField(choices=[('seo_meta', 'SEO Meta Generation'), ('seo_meta_bulk', 'SEO Meta Bulk Generation'), ('social_content', 'Social Content Generation')], max_length=30)),
                ('status', models.CharField(choices=[('success', 'Success'), ('error', 'Error'), ('rate_limited', 'Rate Limited')], default='success', max_length=20)),
                ('provider', models.CharField(max_length=30)),
                ('model', models.CharField(max_length=100)),
                ('input_tokens', models.PositiveIntegerField(default=0)),
                ('output_tokens', models.PositiveIntegerField(default=0)),
                ('total_tokens', models.PositiveIntegerField(default=0)),
                ('cost_usd', models.DecimalField(decimal_places=6, default=0, max_digits=10)),
                ('error_message', models.TextField(blank=True)),
                ('duration_ms', models.PositiveIntegerField(default=0, help_text='API call duration in milliseconds')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ai_usage_logs', to=settings.AUTH_USER_MODEL)),
                ('job', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ai_usage_logs', to='jobs.job')),
                ('company', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ai_usage_logs', to='companies.company')),
            ],
            options={
                'verbose_name': 'AI Usage Log',
                'verbose_name_plural': 'AI Usage Logs',
                'db_table': 'ai_usage_logs',
                'ordering': ['-created_at'],
                'indexes': [
                    models.Index(fields=['feature', 'created_at'], name='ai_usage_lo_feature_idx'),
                    models.Index(fields=['user', 'created_at'], name='ai_usage_lo_user_idx'),
                    models.Index(fields=['company', 'created_at'], name='ai_usage_lo_company_idx'),
                    models.Index(fields=['status', 'created_at'], name='ai_usage_lo_status_idx'),
                ],
            },
        ),
    ]
