# Generated by Django 5.2.11 on 2026-03-01 21:00

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ArticleCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=100)),
                ('slug', models.SlugField(max_length=100, unique=True)),
                ('description', models.TextField(blank=True)),
                ('sort_order', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'db_table': 'article_categories',
                'ordering': ['sort_order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('article_id', models.CharField(blank=True, db_index=True, editable=False, help_text='Unique 8-character alphanumeric identifier (generated on save)', max_length=10, unique=True)),
                ('title', models.CharField(max_length=255)),
                ('slug', models.SlugField(max_length=300, unique=True)),
                ('excerpt', models.TextField(blank=True, max_length=500)),
                ('content', models.TextField(blank=True)),
                ('cover_image', models.ImageField(blank=True, upload_to='articles/')),
                ('og_image', models.ImageField(blank=True, upload_to='articles/og/')),
                ('tags', models.JSONField(blank=True, default=list)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('scheduled', 'Scheduled'), ('published', 'Published'), ('archived', 'Archived')], default='draft', max_length=20)),
                ('featured', models.BooleanField(default=False)),
                ('selected_template', models.CharField(choices=[('editorial_hero', 'Editorial Hero'), ('split_magazine', 'Split Magazine'), ('minimal_luxury', 'Minimal Luxury'), ('bold_typography', 'Bold Typography'), ('image_led', 'Image Led'), ('modern_grid', 'Modern Grid')], default='editorial_hero', max_length=30)),
                ('published_at', models.DateTimeField(blank=True, null=True)),
                ('scheduled_publish_at', models.DateTimeField(blank=True, null=True)),
                ('reading_time', models.PositiveSmallIntegerField(default=0)),
                ('views', models.PositiveIntegerField(default=0)),
                ('unique_views', models.PositiveIntegerField(default=0)),
                ('meta_title', models.CharField(blank=True, max_length=70)),
                ('meta_description', models.CharField(blank=True, max_length=160)),
                ('canonical_url', models.URLField(blank=True)),
                ('allow_inline_banners', models.BooleanField(default=True)),
                ('affiliate_disclosure', models.CharField(choices=[('auto', 'Auto'), ('manual', 'Manual'), ('none', 'None')], default='auto', max_length=20)),
                ('sponsored_by', models.CharField(blank=True, max_length=100)),
                ('preview_token', models.UUIDField(blank=True, editable=False, null=True, unique=True)),
                ('preview_expires_at', models.DateTimeField(blank=True, null=True)),
                ('pre_trash_status', models.CharField(blank=True, default='', max_length=20)),
                ('author', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='articles', to=settings.AUTH_USER_MODEL)),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='articles', to='articles.articlecategory')),
            ],
            options={
                'db_table': 'articles',
                'ordering': ['-featured', '-published_at'],
            },
        ),
        migrations.CreateModel(
            name='ArticleView',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('visitor_id', models.CharField(db_index=True, max_length=100)),
                ('ip_address', models.GenericIPAddressField()),
                ('user_agent', models.TextField(blank=True)),
                ('referrer', models.URLField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('article', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='view_records', to='articles.article')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'article_views',
            },
        ),
        migrations.AddIndex(
            model_name='article',
            index=models.Index(fields=['status', 'published_at'], name='articles_status_35ee01_idx'),
        ),
        migrations.AddIndex(
            model_name='article',
            index=models.Index(fields=['status', 'scheduled_publish_at'], name='articles_status_dcca47_idx'),
        ),
        migrations.AddIndex(
            model_name='article',
            index=models.Index(fields=['featured', 'status'], name='articles_feature_792d32_idx'),
        ),
        migrations.AddIndex(
            model_name='article',
            index=models.Index(fields=['category', 'status'], name='articles_categor_ae22a5_idx'),
        ),
        migrations.AddIndex(
            model_name='article',
            index=models.Index(fields=['deleted_at'], name='articles_deleted_656368_idx'),
        ),
        migrations.AddIndex(
            model_name='articleview',
            index=models.Index(fields=['article', 'created_at'], name='article_vie_article_a22609_idx'),
        ),
        migrations.AddIndex(
            model_name='articleview',
            index=models.Index(fields=['visitor_id', 'article'], name='article_vie_visitor_53f2cc_idx'),
        ),
    ]
