# Generated by Django 5.2.11 on 2026-02-25 04:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('audit', '0003_alter_auditlog_action'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auditlog',
            name='action',
            field=models.CharField(choices=[('create', 'Create'), ('update', 'Update'), ('delete', 'Delete'), ('suspend', 'Suspend'), ('activate', 'Activate'), ('verify', 'Verify'), ('approve', 'Approve'), ('reject', 'Reject'), ('grant', 'Grant Credits'), ('revoke', 'Revoke'), ('login', 'Login'), ('logout', 'Logout'), ('impersonate', 'Impersonate'), ('campaign_create', 'Campaign Create'), ('campaign_send', 'Campaign Send'), ('campaign_pause', 'Campaign Pause'), ('campaign_delete', 'Campaign Delete'), ('campaign_approve', 'Campaign Approve'), ('coupon_create', 'Coupon Create'), ('coupon_delete', 'Coupon Delete'), ('coupon_pause', 'Coupon Pause'), ('coupon_activate', 'Coupon Activate'), ('coupon_duplicate', 'Coupon Duplicate'), ('coupon_redeem', 'Coupon Redeem'), ('store_credit_issue', 'Store Credit Issue'), ('payment', 'Payment'), ('coupon_checkout', 'Coupon Applied at Checkout'), ('journey_create', 'Journey Create'), ('journey_activate', 'Journey Activate'), ('journey_pause', 'Journey Pause'), ('journey_archive', 'Journey Archive'), ('journey_duplicate', 'Journey Duplicate'), ('segment_create', 'Segment Create'), ('consent_update', 'Consent Update'), ('suppression_add', 'Suppression Add')], max_length=30),
        ),
    ]
