# Generated by Django 5.2.11 on 2026-02-19 05:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0004_invoice_number_and_pdf_key'),
    ]

    operations = [
        migrations.AddField(
            model_name='package',
            name='team_management',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='currency',
            field=models.CharField(default='CAD', max_length=3),
        ),
        migrations.AlterField(
            model_name='package',
            name='currency',
            field=models.CharField(default='CAD', max_length=3),
        ),
    ]
