# Generated by Django 5.2.11 on 2026-02-19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0005_package_team_management_alter_invoice_currency_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='payment_method',
            field=models.CharField(
                blank=True,
                choices=[
                    ('stripe_card', 'Use stored card'),
                    ('e_transfer', 'E-Transfer received'),
                    ('invoice', 'Send invoice to company'),
                    ('manual_card', 'Card payment (phone/manual)'),
                    ('complimentary', 'Complimentary (no charge)'),
                ],
                default='stripe_card',
                max_length=20,
            ),
        ),
    ]
