# Generated by Django 5.2.11 on 2026-02-25 03:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0007_stripewebhookevent'),
        ('marketing', '0001_initial'),
        ('moderation', '0013_jobpackage_featured_credits_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entitlement',
            name='package',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='moderation.jobpackage'),
        ),
        migrations.AlterField(
            model_name='subscription',
            name='package',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='moderation.jobpackage'),
        ),
        migrations.AlterField(
            model_name='invoiceitem',
            name='package',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='moderation.jobpackage'),
        ),
        migrations.RenameIndex(
            model_name='stripewebhookevent',
            new_name='stripe_webh_status_1f91ca_idx',
            old_name='billing_str_status_idx',
        ),
        migrations.AlterField(
            model_name='promocode',
            name='applicable_packages',
            field=models.ManyToManyField(blank=True, related_name='promo_codes', to='moderation.jobpackage'),
        ),
        migrations.DeleteModel(
            name='Package',
        ),
    ]
