# Generated by Django 5.2.11 on 2026-02-25 04:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0008_alter_entitlement_package_alter_subscription_package_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='paymentmethod',
            name='cardholder_name',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='subscription',
            name='status',
            field=models.CharField(choices=[('active', 'Active'), ('past_due', 'Past Due'), ('canceled', 'Canceled'), ('paused', 'Paused'), ('incomplete', 'Incomplete'), ('incomplete_expired', 'Incomplete Expired')], default='active', max_length=30),
        ),
    ]
