# Generated by Django 5.2.11

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('moderation', '0002_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='FraudAlert',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('type', models.CharField(choices=[('suspicious_activity', 'Suspicious Activity'), ('payment_fraud', 'Payment Fraud'), ('fake_job', 'Fake Job'), ('spam', 'Spam'), ('identity_fraud', 'Identity Fraud'), ('multiple_accounts', 'Multiple Accounts'), ('credential_stuffing', 'Credential Stuffing'), ('fake_listings', 'Fake Listings')], max_length=30)),
                ('severity', models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High'), ('critical', 'Critical')], default='medium', max_length=10)),
                ('status', models.CharField(choices=[('open', 'Open'), ('investigating', 'Investigating'), ('resolved', 'Resolved'), ('false_positive', 'False Positive'), ('blocked', 'Blocked')], default='open', max_length=20)),
                ('subject_type', models.CharField(choices=[('user', 'User'), ('company', 'Company'), ('agency', 'Agency'), ('job', 'Job')], max_length=20)),
                ('subject_id', models.PositiveIntegerField()),
                ('subject_name', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('indicators', models.JSONField(blank=True, default=list)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('affected_accounts', models.JSONField(blank=True, default=list)),
                ('detected_at', models.DateTimeField(auto_now_add=True)),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
                ('resolution_notes', models.TextField(blank=True)),
                ('resolved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='resolved_fraud_alerts', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'fraud_alerts',
                'ordering': ['-created_at'],
                'indexes': [
                    models.Index(fields=['status', 'severity'], name='fraud_alert_status_sev_idx'),
                    models.Index(fields=['type', 'status'], name='fraud_alert_type_status_idx'),
                ],
            },
        ),
    ]
