# Generated by Django 5.2.11 on 2026-02-15 06:57
# Modified to handle tables that already exist in the database.

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('moderation', '0003_fraudalert'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        # --- Tables that DO NOT exist yet: create normally ---
        migrations.CreateModel(
            name='AffiliateLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=200)),
                ('company', models.CharField(blank=True, max_length=200)),
                ('url', models.URLField()),
                ('placement', models.CharField(choices=[('job_detail', 'Job Detail'), ('search_results', 'Search Results'), ('email', 'Email'), ('footer', 'Footer')], max_length=50)),
                ('disclosure_label', models.CharField(default='Sponsored', max_length=100)),
                ('is_active', models.BooleanField(default=True)),
                ('clicks', models.IntegerField(default=0)),
                ('conversions', models.IntegerField(default=0)),
                ('revenue', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
            ],
            options={
                'db_table': 'affiliate_links',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='FeatureFlag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=200)),
                ('key', models.CharField(max_length=100, unique=True)),
                ('description', models.TextField(blank=True)),
                ('enabled', models.BooleanField(default=False)),
                ('environment', models.CharField(choices=[('all', 'All'), ('production', 'Production'), ('staging', 'Staging'), ('development', 'Development')], default='all', max_length=20)),
                ('rollout_percentage', models.IntegerField(default=100)),
            ],
            options={
                'db_table': 'feature_flags',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='JobPackage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=200)),
                ('credits', models.IntegerField(default=1)),
                ('validity_days', models.IntegerField(default=30)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('payment_type', models.CharField(choices=[('one_time', 'One Time'), ('subscription', 'Subscription')], default='one_time', max_length=20)),
                ('features', models.JSONField(default=list)),
                ('is_active', models.BooleanField(default=True)),
                ('sort_order', models.IntegerField(default=0)),
            ],
            options={
                'db_table': 'job_packages',
                'ordering': ['sort_order', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PlatformSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('platform_name', models.CharField(default='Orion', max_length=200)),
                ('platform_description', models.TextField(blank=True, default='')),
                ('support_email', models.EmailField(default='support@orion.com', max_length=254)),
                ('timezone', models.CharField(default='UTC', max_length=50)),
                ('maintenance_mode', models.BooleanField(default=False)),
                ('maintenance_message', models.TextField(blank=True, default='')),
                ('job_default_duration_days', models.IntegerField(default=30)),
                ('job_max_duration_days', models.IntegerField(default=90)),
                ('job_max_per_company', models.IntegerField(default=25)),
                ('job_salary_required', models.BooleanField(default=False)),
                ('job_auto_approve_verified', models.BooleanField(default=True)),
                ('job_enable_refresh', models.BooleanField(default=True)),
                ('job_enable_spam_detection', models.BooleanField(default=True)),
                ('job_block_duplicates', models.BooleanField(default=True)),
                ('job_blocked_keywords', models.TextField(blank=True, default='scam\nget rich quick\nno experience needed\nmake money fast')),
                ('billing_provider', models.CharField(default='stripe', max_length=20)),
                ('billing_default_currency', models.CharField(default='usd', max_length=10)),
                ('billing_invoice_prefix', models.CharField(default='INV-', max_length=20)),
                ('billing_company_name', models.CharField(default='Orion Jobs Inc.', max_length=255)),
                ('billing_company_address', models.TextField(blank=True, default='')),
                ('integration_google_analytics_id', models.CharField(blank=True, default='', max_length=50)),
                ('integration_mixpanel_token', models.CharField(blank=True, default='', max_length=100)),
                ('require_2fa', models.BooleanField(default=False)),
                ('session_timeout_minutes', models.IntegerField(default=60)),
                ('max_login_attempts', models.IntegerField(default=5)),
                ('enable_ip_allowlist', models.BooleanField(default=False)),
                ('ip_allowlist', models.TextField(blank=True, default='')),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Platform Settings',
                'verbose_name_plural': 'Platform Settings',
                'db_table': 'platform_settings_singleton',
            },
        ),
        migrations.CreateModel(
            name='SponsoredBanner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=200)),
                ('image_url', models.URLField(blank=True)),
                ('target_url', models.URLField()),
                ('placement', models.CharField(choices=[('search_top', 'Search Top'), ('search_sidebar', 'Search Sidebar'), ('job_detail', 'Job Detail'), ('homepage', 'Homepage')], max_length=50)),
                ('sponsor', models.CharField(blank=True, max_length=200)),
                ('is_active', models.BooleanField(default=True)),
                ('start_date', models.DateField(blank=True, null=True)),
                ('end_date', models.DateField(blank=True, null=True)),
                ('impressions', models.IntegerField(default=0)),
                ('clicks', models.IntegerField(default=0)),
            ],
            options={
                'db_table': 'sponsored_banners',
                'ordering': ['-created_at'],
            },
        ),

        # --- Tables that ALREADY exist (fraud_rules, compliance_requests): ---
        # Use SeparateDatabaseAndState so Django tracks the model state
        # without trying to CREATE TABLE again.
        migrations.SeparateDatabaseAndState(
            state_operations=[
                migrations.CreateModel(
                    name='FraudRule',
                    fields=[
                        ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                        ('created_at', models.DateTimeField(auto_now_add=True)),
                        ('updated_at', models.DateTimeField(auto_now=True)),
                        ('name', models.CharField(max_length=255)),
                        ('description', models.TextField()),
                        ('enabled', models.BooleanField(default=True)),
                        ('severity', models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High'), ('critical', 'Critical')], default='medium', max_length=10)),
                        ('conditions', models.JSONField(default=dict)),
                        ('triggers_count', models.PositiveIntegerField(default=0)),
                        ('false_positives_count', models.PositiveIntegerField(default=0)),
                    ],
                    options={
                        'db_table': 'fraud_rules',
                        'ordering': ['-created_at'],
                    },
                ),
                migrations.CreateModel(
                    name='ComplianceRequest',
                    fields=[
                        ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                        ('created_at', models.DateTimeField(auto_now_add=True)),
                        ('updated_at', models.DateTimeField(auto_now=True)),
                        ('type', models.CharField(choices=[('gdpr_access', 'GDPR Data Access'), ('gdpr_delete', 'GDPR Data Deletion'), ('gdpr_portability', 'GDPR Data Portability'), ('ccpa_access', 'CCPA Data Access'), ('ccpa_delete', 'CCPA Data Deletion'), ('ccpa_opt_out', 'CCPA Opt-Out')], max_length=30)),
                        ('status', models.CharField(choices=[('pending', 'Pending'), ('in_progress', 'In Progress'), ('completed', 'Completed'), ('rejected', 'Rejected')], default='pending', max_length=20)),
                        ('reason', models.TextField(blank=True)),
                        ('notes', models.TextField(blank=True)),
                        ('submitted_at', models.DateTimeField(auto_now_add=True)),
                        ('due_at', models.DateTimeField()),
                        ('completed_at', models.DateTimeField(blank=True, null=True)),
                        ('verification_code', models.CharField(blank=True, max_length=64)),
                        ('verified_at', models.DateTimeField(blank=True, null=True)),
                        ('export_file', models.FileField(blank=True, null=True, upload_to='compliance_exports/')),
                        ('processed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='processed_compliance_requests', to=settings.AUTH_USER_MODEL)),
                        ('requester', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='compliance_requests', to=settings.AUTH_USER_MODEL)),
                    ],
                    options={
                        'db_table': 'compliance_requests',
                        'ordering': ['-submitted_at'],
                    },
                ),
            ],
            database_operations=[],
        ),
    ]
