# Generated by Django 5.2.11 on 2026-02-19 05:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('moderation', '0004_affiliatelink_featureflag_fraudrule_jobpackage_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobpackage',
            name='currency',
            field=models.CharField(default='CAD', max_length=3),
        ),
        migrations.AddField(
            model_name='jobpackage',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='jobpackage',
            name='disable_repeat_purchase',
            field=models.BooleanField(default=False, help_text='If true, a customer can only purchase this package once (e.g., free trials, welcome offers).'),
        ),
        migrations.AddField(
            model_name='jobpackage',
            name='is_popular',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='jobpackage',
            name='monthly_price',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Monthly subscription price. Required for subscription packages.', max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='jobpackage',
            name='package_validity_days',
            field=models.PositiveIntegerField(blank=True, help_text='How long the package/entitlement is valid after purchase (days). Null = never expires.', null=True),
        ),
        migrations.AddField(
            model_name='jobpackage',
            name='sale_price',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Discounted price. If set, the original price is shown as struck-through.', max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='jobpackage',
            name='slug',
            field=models.SlugField(blank=True, max_length=200, unique=True),
        ),
        migrations.AddField(
            model_name='jobpackage',
            name='tax_rate',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Tax percentage (e.g., 13.00 for 13% HST). 0 means tax-exempt.', max_digits=5),
        ),
        migrations.AddField(
            model_name='jobpackage',
            name='yearly_price',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Yearly subscription price (total per year, not per month). Required for subscription packages.', max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='fraudalert',
            name='type',
            field=models.CharField(choices=[('suspicious_activity', 'Suspicious Activity'), ('payment_fraud', 'Payment Fraud'), ('fake_job', 'Fake Job'), ('spam', 'Spam'), ('identity_fraud', 'Identity Fraud'), ('multiple_accounts', 'Multiple Accounts'), ('credential_stuffing', 'Credential Stuffing'), ('fake_listings', 'Fake Listings'), ('disposable_email', 'Disposable Email')], max_length=30),
        ),
        migrations.AlterField(
            model_name='jobpackage',
            name='payment_type',
            field=models.CharField(choices=[('one_time', 'One Time'), ('subscription', 'Subscription'), ('bundle', 'Credit Bundle')], default='one_time', max_length=20),
        ),
        migrations.AlterField(
            model_name='jobpackage',
            name='validity_days',
            field=models.IntegerField(default=30, help_text='How long each job post stays live (days)'),
        ),
    ]
