# Generated by Django 5.2.11 on 2026-02-24 07:06

from django.db import migrations, models
import core.encryption


class Migration(migrations.Migration):

    dependencies = [
        ('moderation', '0012_create_fraud_rules_table'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobpackage',
            name='featured_credits',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='jobpackage',
            name='priority_support',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='jobpackage',
            name='social_credits',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='jobpackage',
            name='stripe_price_id',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AddField(
            model_name='jobpackage',
            name='stripe_product_id',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AddField(
            model_name='jobpackage',
            name='team_management',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='platformsettings',
            name='stripe_publishable_key',
            field=core.encryption.EncryptedTextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='platformsettings',
            name='stripe_secret_key',
            field=core.encryption.EncryptedTextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='platformsettings',
            name='stripe_webhook_secret',
            field=core.encryption.EncryptedTextField(blank=True, default=''),
        ),
    ]
