# Generated by Django 5.2.11 on 2026-03-03 05:21

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('moderation', '0015_create_compliance_requests_table'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='RetentionRule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('category', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('retention_days', models.PositiveIntegerField(help_text='Number of days to retain data (e.g., 1095 for 3 years)')),
                ('is_deletable', models.BooleanField(default=False, help_text='Whether users can request deletion of this data category')),
                ('is_active', models.BooleanField(default=True)),
                ('enforcement', models.CharField(choices=[('manual', 'Manual'), ('automated', 'Automated'), ('legal_hold', 'Legal Hold')], default='manual', max_length=20)),
                ('legal_basis', models.CharField(blank=True, max_length=200)),
                ('sort_order', models.PositiveIntegerField(default=0)),
            ],
            options={
                'db_table': 'retention_rules',
                'ordering': ['sort_order', 'category'],
            },
        ),
        migrations.CreateModel(
            name='LegalDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=200)),
                ('slug', models.SlugField(unique=True)),
                ('document_type', models.CharField(choices=[('privacy_policy', 'Privacy Policy'), ('terms_of_service', 'Terms of Service'), ('cookie_policy', 'Cookie Policy'), ('dpa', 'Data Processing Agreement'), ('acceptable_use', 'Acceptable Use Policy'), ('other', 'Other')], max_length=30)),
                ('content', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('published', 'Published'), ('archived', 'Archived')], default='draft', max_length=20)),
                ('version', models.CharField(default='1.0', max_length=20)),
                ('published_at', models.DateTimeField(blank=True, null=True)),
                ('effective_date', models.DateField(blank=True, null=True)),
                ('last_reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('public_url', models.URLField(blank=True)),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_legal_documents', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'legal_documents',
                'ordering': ['-updated_at'],
            },
        ),
    ]
