# Generated by Django 5.2.11 on 2026-02-06 04:20

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('jobs', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='posted_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='posted_jobs', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='jobbookmark',
            name='candidate',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bookmarked_by_jobs', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='jobbookmark',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='job_bookmarks_created', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='jobbookmark',
            name='job',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bookmarks', to='jobs.job'),
        ),
        migrations.AddField(
            model_name='jobreport',
            name='job',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reports', to='jobs.job'),
        ),
        migrations.AddField(
            model_name='jobreport',
            name='reporter',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='job_reports', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='jobreport',
            name='reviewed_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_job_reports', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='jobview',
            name='job',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='view_records', to='jobs.job'),
        ),
        migrations.AddField(
            model_name='jobview',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='job',
            index=models.Index(fields=['status', 'posted_at'], name='jobs_status_552bc6_idx'),
        ),
        migrations.AddIndex(
            model_name='job',
            index=models.Index(fields=['company', 'status'], name='jobs_company_0582d9_idx'),
        ),
        migrations.AddIndex(
            model_name='job',
            index=models.Index(fields=['category', 'status'], name='jobs_categor_baa678_idx'),
        ),
        migrations.AddIndex(
            model_name='job',
            index=models.Index(fields=['location_type', 'status'], name='jobs_locatio_4d1105_idx'),
        ),
        migrations.AddIndex(
            model_name='job',
            index=models.Index(fields=['expires_at'], name='jobs_expires_503a37_idx'),
        ),
        migrations.AddIndex(
            model_name='job',
            index=models.Index(fields=['featured', 'status'], name='jobs_feature_c81d77_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='jobbookmark',
            unique_together={('job', 'candidate')},
        ),
        migrations.AddIndex(
            model_name='jobreport',
            index=models.Index(fields=['job', 'status'], name='job_reports_job_id_8dd435_idx'),
        ),
        migrations.AddIndex(
            model_name='jobreport',
            index=models.Index(fields=['status', 'created_at'], name='job_reports_status_2d0413_idx'),
        ),
        migrations.AddIndex(
            model_name='jobview',
            index=models.Index(fields=['job', 'created_at'], name='job_views_job_id_8b0d41_idx'),
        ),
        migrations.AddIndex(
            model_name='jobview',
            index=models.Index(fields=['visitor_id', 'job'], name='job_views_visitor_7496e0_idx'),
        ),
    ]
