# Generated by Django 5.2.11 on 2026-02-19 05:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='salary_currency',
            field=models.CharField(default='CAD', max_length=3),
        ),
    ]
