# Generated by Django 5.2.11 on 2026-02-19 20:57

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0010_agency_allow_backdate_posting'),
        ('jobs', '0003_alter_job_salary_currency'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='scheduled_publish_at',
            field=models.DateTimeField(blank=True, help_text='When to auto-publish this job', null=True),
        ),
        migrations.AlterField(
            model_name='job',
            name='status',
            field=models.CharField(choices=[('draft', 'Draft'), ('pending', 'Pending Review'), ('scheduled', 'Scheduled'), ('published', 'Published'), ('paused', 'Paused'), ('expired', 'Expired'), ('hidden', 'Hidden')], default='draft', max_length=20),
        ),
        migrations.AddIndex(
            model_name='job',
            index=models.Index(fields=['status', 'scheduled_publish_at'], name='jobs_status_babce9_idx'),
        ),
    ]
