# Generated by Django 5.2.11 on 2026-02-23 02:40

import core.utils
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0008_fix_entity_id_callable_default'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='job_id',
            field=models.CharField(db_index=True, default=core.utils.generate_entity_id, editable=False, help_text='Unique 8-character alphanumeric identifier', max_length=10, unique=True),
        ),
        migrations.AlterField(
            model_name='job',
            name='status',
            field=models.CharField(choices=[('draft', 'Draft'), ('pending', 'Pending Review'), ('pending_payment', 'Pending Payment'), ('scheduled', 'Scheduled'), ('published', 'Published'), ('paused', 'Paused'), ('expired', 'Expired'), ('filled', 'Filled'), ('hidden', 'Hidden')], default='draft', max_length=20),
        ),
    ]
