# Generated by Django 5.2.11 on 2026-02-27 05:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0010_add_address_postal_code_to_job'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='expires_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='job',
            name='job_id',
            field=models.CharField(blank=True, db_index=True, editable=False, help_text='Unique 8-character alphanumeric identifier (generated on save)', max_length=10, unique=True),
        ),
    ]
