# Generated by Django 5.2.11 on 2026-02-06 04:20

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=255)),
                ('slug', models.SlugField(max_length=255, unique=True)),
                ('domain', models.CharField(blank=True, max_length=255)),
                ('logo', models.FileField(blank=True, null=True, upload_to='company_logos/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['svg', 'png', 'jpg', 'jpeg', 'webp'])])),
                ('banner', models.FileField(blank=True, null=True, upload_to='company_banners/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['svg', 'png', 'jpg', 'jpeg', 'webp'])])),
                ('description', models.TextField(blank=True)),
                ('tagline', models.CharField(blank=True, max_length=255)),
                ('website', models.URLField(blank=True)),
                ('industry', models.CharField(blank=True, choices=[('Technology', 'Technology'), ('Finance & Banking', 'Finance & Banking'), ('Healthcare', 'Healthcare'), ('Retail', 'Retail'), ('Sales', 'Sales'), ('Manufacturing', 'Manufacturing'), ('Education', 'Education'), ('Energy & Utilities', 'Energy & Utilities'), ('Media & Entertainment', 'Media & Entertainment'), ('Real Estate', 'Real Estate'), ('Transportation & Logistics', 'Transportation & Logistics'), ('Construction', 'Construction'), ('Hospitality & Tourism', 'Hospitality & Tourism'), ('Legal Services', 'Legal Services'), ('Nonprofit', 'Nonprofit'), ('Government', 'Government'), ('Agriculture', 'Agriculture'), ('Telecommunications', 'Telecommunications'), ('Professional Services', 'Professional Services'), ('Consumer Goods', 'Consumer Goods'), ('Automotive', 'Automotive'), ('Aerospace & Defense', 'Aerospace & Defense'), ('Pharmaceuticals', 'Pharmaceuticals'), ('Insurance', 'Insurance'), ('Food & Beverage', 'Food & Beverage'), ('Fashion & Apparel', 'Fashion & Apparel'), ('E-commerce', 'E-commerce'), ('Consulting', 'Consulting'), ('Marketing & Advertising', 'Marketing & Advertising'), ('Human Resources', 'Human Resources'), ('Mining & Metals', 'Mining & Metals'), ('Environmental Services', 'Environmental Services'), ('Sports & Recreation', 'Sports & Recreation'), ('Arts & Design', 'Arts & Design'), ('Security & Investigations', 'Security & Investigations'), ('Venture Capital & Private Equity', 'Venture Capital & Private Equity'), ('Staffing & Recruiting', 'Staffing & Recruiting'), ('Biotechnology', 'Biotechnology'), ('Logistics & Supply Chain', 'Logistics & Supply Chain'), ('Information Services', 'Information Services'), ('Other', 'Other')], max_length=100)),
                ('size', models.CharField(blank=True, choices=[('1-10', '1-10 employees'), ('11-50', '11-50 employees'), ('51-200', '51-200 employees'), ('201-500', '201-500 employees'), ('501-1000', '501-1000 employees'), ('1001-5000', '1001-5000 employees'), ('5001+', '5001+ employees')], max_length=20)),
                ('founded_year', models.PositiveIntegerField(blank=True, null=True)),
                ('headquarters_city', models.CharField(blank=True, max_length=100)),
                ('headquarters_state', models.CharField(blank=True, max_length=100)),
                ('headquarters_country', models.CharField(blank=True, max_length=100)),
                ('linkedin_url', models.URLField(blank=True)),
                ('twitter_url', models.URLField(blank=True)),
                ('facebook_url', models.URLField(blank=True)),
                ('status', models.CharField(choices=[('verified', 'Verified'), ('pending', 'Pending Verification'), ('unverified', 'Unverified')], default='pending', max_length=20)),
                ('billing_status', models.CharField(choices=[('active', 'Active'), ('suspended', 'Suspended'), ('trial', 'Trial')], default='trial', max_length=20)),
                ('risk_level', models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High')], default='low', max_length=20)),
                ('stripe_customer_id', models.CharField(blank=True, max_length=100)),
            ],
            options={
                'verbose_name_plural': 'Companies',
                'db_table': 'companies',
            },
        ),
        migrations.CreateModel(
            name='CompanyUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('role', models.CharField(choices=[('owner', 'Owner'), ('admin', 'Admin'), ('recruiter', 'Recruiter'), ('viewer', 'Viewer')], default='viewer', max_length=20)),
                ('invited_at', models.DateTimeField(blank=True, null=True)),
                ('joined_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'company_users',
            },
        ),
        migrations.CreateModel(
            name='Agency',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=255)),
                ('slug', models.SlugField(max_length=255, unique=True)),
                ('logo', models.FileField(blank=True, null=True, upload_to='agency_logos/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['svg', 'png', 'jpg', 'jpeg', 'webp'])])),
                ('description', models.TextField(blank=True)),
                ('website', models.URLField(blank=True)),
                ('specializations', models.JSONField(blank=True, default=list)),
                ('city', models.CharField(blank=True, max_length=100)),
                ('state', models.CharField(blank=True, max_length=100)),
                ('country', models.CharField(blank=True, max_length=100)),
                ('status', models.CharField(choices=[('verified', 'Verified'), ('pending', 'Pending Verification'), ('unverified', 'Unverified')], default='pending', max_length=20)),
                ('billing_status', models.CharField(choices=[('active', 'Active'), ('suspended', 'Suspended'), ('trial', 'Trial')], default='trial', max_length=20)),
                ('billing_model', models.CharField(choices=[('agency_pays', 'Agency Pays'), ('company_pays', 'Company Pays')], default='agency_pays', max_length=20)),
                ('stripe_customer_id', models.CharField(blank=True, max_length=100)),
            ],
            options={
                'verbose_name_plural': 'Agencies',
                'db_table': 'agencies',
                'indexes': [models.Index(fields=['slug'], name='agencies_slug_96227a_idx'), models.Index(fields=['status'], name='agencies_status_e99f80_idx'), models.Index(fields=['billing_status'], name='agencies_billing_98496f_idx')],
            },
        ),
        migrations.CreateModel(
            name='AgencyClient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('notes', models.TextField(blank=True)),
                ('agency', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='clients', to='companies.agency')),
            ],
            options={
                'db_table': 'agency_clients',
            },
        ),
        migrations.CreateModel(
            name='AgencyUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('role', models.CharField(choices=[('owner', 'Owner'), ('admin', 'Admin'), ('recruiter', 'Recruiter'), ('viewer', 'Viewer')], default='viewer', max_length=20)),
                ('agency', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='members', to='companies.agency')),
            ],
            options={
                'db_table': 'agency_users',
            },
        ),
    ]
