# Generated by Django 5.2.11 on 2026-02-06 05:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='agency',
            name='contact_email',
            field=models.EmailField(blank=True, max_length=254),
        ),
        migrations.AddField(
            model_name='agency',
            name='industry',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
