# Generated by Django 5.2.11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0003_agency_contact_email_agency_industry'),
    ]

    operations = [
        migrations.AddField(
            model_name='agency',
            name='risk_level',
            field=models.CharField(
                choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High')],
                default='low',
                max_length=20,
            ),
        ),
    ]
