# Generated by Django 5.2.11 on 2026-02-10 20:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0004_agency_risk_level'),
    ]

    operations = [
        migrations.CreateModel(
            name='CompanySettings',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('company', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='settings', serialize=False, to='companies.company')),
                ('job_defaults', models.JSONField(blank=True, default=dict, help_text='Job posting defaults: default_duration, default_apply_method, require_salary, etc.')),
                ('notification_preferences', models.JSONField(blank=True, default=dict, help_text='Email notification settings: email_new_applications, email_job_published, etc.')),
            ],
            options={
                'db_table': 'company_settings',
            },
        ),
    ]
