# Generated by Django 5.2.11 on 2026-02-10 21:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0005_companysettings'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='headquarters_address',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='company',
            name='headquarters_postal_code',
            field=models.CharField(blank=True, max_length=20),
        ),
    ]
