# Generated by Django 5.2.11 on 2026-02-11 01:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0006_add_address_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='instagram_url',
            field=models.URLField(blank=True),
        ),
    ]
