# Generated by Django 5.2.11 on 2026-02-18 16:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0007_company_instagram_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='agency',
            name='team_management_enabled',
            field=models.BooleanField(
                default=True,
                help_text='Admin override: enable/disable team management for this agency',
            ),
        ),
        migrations.AddField(
            model_name='agency',
            name='featured',
            field=models.BooleanField(
                default=False,
                help_text='Show this agency in featured listings',
            ),
        ),
    ]
