# Generated by Django 5.2.11 on 2026-02-19 05:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0008_add_agency_team_management_and_featured'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='team_management_enabled',
            field=models.BooleanField(default=False, help_text='Admin override: enable team management regardless of package'),
        ),
    ]
