# Generated by Django 5.2.11 on 2026-02-19 20:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0009_company_team_management_enabled'),
    ]

    operations = [
        migrations.AddField(
            model_name='agency',
            name='allow_backdate_posting',
            field=models.BooleanField(default=False, help_text='Allow this agency to backdate job postings up to 5 months in the past'),
        ),
    ]
