# Generated by Django 5.2.11 on 2026-02-27 05:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0013_alter_agency_entity_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='agency',
            name='entity_id',
            field=models.CharField(blank=True, db_index=True, editable=False, help_text='Unique 8-character alphanumeric identifier (generated on save)', max_length=10, unique=True),
        ),
        migrations.AlterField(
            model_name='company',
            name='entity_id',
            field=models.CharField(blank=True, db_index=True, editable=False, help_text='Unique 8-character alphanumeric identifier (generated on save)', max_length=10, unique=True),
        ),
        migrations.AlterField(
            model_name='companysettings',
            name='job_defaults',
            field=models.JSONField(blank=True, default=dict, help_text='Job posting defaults: default_apply_method, require_salary, etc.'),
        ),
    ]
