# Generated by Django 5.2.11 on 2026-02-25 03:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketing', '0001_initial'),
        ('moderation', '0013_jobpackage_featured_credits_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coupon',
            name='applicable_packages',
            field=models.ManyToManyField(blank=True, related_name='marketing_coupons', to='moderation.jobpackage'),
        ),
    ]
