# Generated by Django 5.2.11 on 2026-02-25 04:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketing', '0002_alter_coupon_applicable_packages'),
    ]

    operations = [
        migrations.AddField(
            model_name='coupon',
            name='stripe_coupon_id',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
    ]
